<?xml version="1.0"?>

<robot name="arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.1415926535897931"/>

  <!-- Arm properties -->
  <xacro:property name="arm_mass"           value="0.03"/>
  <xacro:property name="hook_mass"          value="0.01"/>

  <xacro:property name="alpha"              value="${PI/8}"/>

  <xacro:property name="arm_base_width"     value="0.03"/>
  <xacro:property name="arm_base_height"    value="0.02"/>

  <xacro:property name="arm_hand_length"    value="0.06"/>
  <xacro:property name="arm_hand_width"     value="0.01"/>

  <xacro:property name="arm_hook_length"    value="0.04"/>
  <xacro:property name="arm_hook_width"     value="0.006"/>

  <!-- Box inertial matrix -->
  <xacro:macro name="box_inertial" params="mass length width heigth">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${ 0.083 * mass * (width*width + heigth*heigth) }"
        ixy="0.0"
        ixz="0.0"
        iyy="${0.083 * mass * (length*length + heigth*heigth)}"
        iyz="0.0"
        izz="${0.083 * mass * (length*length + width*width)}"/>
    </inertial>
  </xacro:macro>


  <!-- Begin arm joints and links -->

  <link name="arm_base">
    <visual>
      <origin rpy="0.0 0 0" xyz="0 0 0.0"/>
      <geometry>
        <box size="${arm_base_width} ${arm_base_width} ${arm_base_height}"/>
      </geometry>
    </visual>
    <xacro:box_inertial mass="${arm_mass}" length="${arm_base_width}" width="${arm_base_width}" heigth="${arm_base_height}"/>
    <buoyancy><compensation>1.0</compensation></buoyancy>
  </link>

  <joint name="base_link_to_arm_base" type="fixed">
    <parent link="base_link"/>
    <child link="arm_base"/>
    <origin rpy="0 0 0" xyz="0 0 0.9"/>
  </joint>


  <link name="arm_hand">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${arm_hand_length/2}"/>
      <geometry>
        <cylinder radius="${arm_hand_width}" length="${arm_hand_length}"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${arm_hand_length/2}"/>
      <geometry>
        <cylinder radius="${arm_hand_width}" length="${arm_hand_length}"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 ${arm_hand_length/2}"/>
      <mass value="${arm_mass}"/>
      <inertia
        ixx="0.1"
        ixy="0.0"
        ixz="0.0"
        iyy="0.1"
        iyz="0.0"
        izz="0.1"/>
    </inertial>
    <buoyancy><compensation>1.0</compensation></buoyancy>
  </link>

  <joint name="arm_base_to_arm_hand" type="fixed">
    <parent link="arm_base"/>
    <child link="arm_hand"/>
    <origin rpy="${alpha} 0 0" xyz="0 0 ${arm_base_height/2}"/>
  </joint>


  <link name="arm_hook0">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${-arm_hook_length/2}"/>
      <geometry>
        <cylinder radius="${arm_hook_width}" length="${arm_hook_length}"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${-arm_hook_length/2}"/>
      <geometry>
        <cylinder radius="${arm_hook_width}" length="${arm_hook_length}"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 ${arm_hook_length/2}"/>
      <mass value="${hook_mass}"/>
      <inertia
        ixx="0.1"
        ixy="0.0"
        ixz="0.0"
        iyy="0.1"
        iyz="0.0"
        izz="0.1"/>
    </inertial>
  </link>

  <joint name="OpenHook" type="revolute">
    <parent link="arm_hand"/>
    <child link="arm_hook0"/>
    <axis xyz="1 0 0"/>
    <origin rpy="${PI/2-alpha} 0 0" xyz="0 0 ${arm_hand_length}"/>
    <dynamics damping="0.8"/>
    <limit lower="0" upper="${PI/2}" velocity="1" effort="500"/>
  </joint>


  <link name="arm_hook1">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${arm_hook_length/4}"/>
      <geometry>
        <cylinder radius="${arm_hook_width}" length="${arm_hook_length/2}"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${arm_hook_length/4}"/>
      <geometry>
        <cylinder radius="${arm_hook_width}" length="${arm_hook_length/2}"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 ${arm_hook_length/4}"/>
      <mass value="${hook_mass}"/>
      <inertia
        ixx="0.1"
        ixy="0.0"
        ixz="0.0"
        iyy="0.1"
        iyz="0.0"
        izz="0.1"/>
    </inertial>
  </link>

  <joint name="hook0_to_hook1" type="fixed">
    <parent link="arm_hook0"/>
    <child link="arm_hook1"/>
    <origin rpy="${11*PI/12} 0 0" xyz="0 0 ${-arm_hook_length}"/>
  </joint>
</robot>
