<?xml version="1.0"?>

<robot name="mayak" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.1415926535897931"/>

  <!-- Mayak properties -->
  <xacro:property name="width"      value="0.05"/>
  <xacro:property name="height"     value="0.04"/>
  <xacro:property name="box_height" value="0.08"/>

  <xacro:property name="radius"     value="0.01"/>
  <xacro:property name="radius1"    value="0.005"/>

  <xacro:property name="hand_mass"  value="0.01"/>
  <xacro:property name="mayak_mass" value="0.8"/>

  <!-- Cylinder inertial matrix -->
  <xacro:macro name="cyl_inertial" params="mass radius length">
    <inertia
      ixx="${mass*(radius*radius/4+length*length/12)}"
      ixy="0.0"
      ixz="0.0"
      iyy="${mass*(radius*radius/4+length*length/12)}"
      iyz="0.0"
      izz="${mass*radius*radius/2}"/>
  </xacro:macro>

  <static>true</static>

  <link name="hand_base">
    <visual>
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="${radius}" length="${width}"/>
      </geometry>
    </visual>

    <inertial>
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <mass value="${hand_mass}"/>
      <inertia
        ixx="0.1"
        ixy="0.0"
        ixz="0.0"
        iyy="0.1"
        iyz="0.0"
        izz="0.1"/>
    </inertial>

    <collision>
      <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
      <geometry>
        <cylinder radius="${radius}" length="${width}"/>
      </geometry>
    </collision>

    <buoyancy>
      <compensation>0</compensation>
      <damping xyz="0 0 0"/>
    </buoyancy>
  </link>


  <link name="hand_right">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${-width/2}"/>
      <geometry>
        <cylinder radius="${radius1}" length="${width}"/>
      </geometry>
    </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 ${-width/2}"/>
      <mass value="${hand_mass}"/>
      <xacro:cyl_inertial mass="${hand_mass}" radius="${radius}" length="${width}"/>
    </inertial>

    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${-width/2}"/>
      <geometry>
        <cylinder radius="${radius1}" length="${width}"/>
      </geometry>
    </collision>
  </link>

  <joint name="hand_base_to_right_hand" type="fixed">
    <parent link="hand_base"/>
    <child link="hand_right"/>
    <origin rpy="0 0 0" xyz="${width/2-radius1/2} 0 0"/>
  </joint>


  <link name="hand_left">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${-width/2}"/>
      <geometry>
        <cylinder radius="${radius1}" length="${width}"/>
      </geometry>
    </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 ${-width/2}"/>
      <mass value="${hand_mass}"/>
      <xacro:cyl_inertial mass="${hand_mass}" radius="${radius}" length="${width}"/>
    </inertial>

    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${-width/2}"/>
      <geometry>
        <cylinder radius="${radius1}" length="${width}"/>
      </geometry>
    </collision>
  </link>

  <joint name="hand_base_to_left_hand" type="fixed">
    <parent link="hand_base"/>
    <child link="hand_left"/>
    <origin rpy="0 0 0" xyz="${-width/2+radius1/2} 0 0"/>
  </joint>


  <link name="base">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${-box_height/2}"/>
      <geometry>
        <box size="${width} ${width} ${box_height}"/>
      </geometry>
    </visual>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 ${-box_height/2}"/>
      <mass value="${mayak_mass}"/>
      <inertia
        ixx="0.1"
        ixy="0.0"
        ixz="0.0"
        iyy="0.1"
        iyz="0.0"
        izz="0.1"/>
    </inertial>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${-width/2}"/>
      <geometry>
        <box size="${width} ${width} ${box_height}"/>
      </geometry>
    </collision>
  </link>

  <joint name="hand_base_to_base" type="fixed">
    <parent link="hand_base"/>
    <child link="base"/>
    <origin rpy="0 0 0" xyz="0 0 ${-width}"/>
  </joint>
</robot>
