<?xml version="1.0"?>

<robot name="mayaki" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.1415926535897931"/>

  <!-- Arm properties -->
  <xacro:property name="arm_mass"           value="0.03"/>
  <xacro:property name="arm_base_size"      value="0.05"/>
  <xacro:property name="arm_shoulder_size"  value="0.15"/>
  <xacro:property name="arm_hand_size"      value="0.08"/>
  <xacro:property name="alpha"              value="${PI/8}"/>

  <!-- Box inertial matrix -->
  <xacro:macro name="box_inertial" params="mass length width heigth">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${ 0.083 * mass * (width*width + heigth*heigth) }"
        ixy="0.0"
        ixz="0.0"
        iyy="${0.083 * mass * (length*length + heigth*heigth)}"
        iyz="0.0"
        izz="${0.083 * mass * (length*length + width*width)}"/>
    </inertial>
  </xacro:macro>


  <!-- Begin arm joints and links -->
  <link name="arm_base">
    <visual>
      <origin rpy="0.0 0 0" xyz="0 0 0.0"/>
      <geometry>
        <box size="${arm_base_size} ${arm_base_size} ${arm_base_size}"/>
      </geometry>
    </visual>

    <xacro:box_inertial mass="${arm_mass}" length="${arm_base_size}" width="${arm_base_size}" heigth="${arm_base_size}"/>

    <buoyancy><compensation>1.0</compensation></buoyancy>
  </link>

  <joint name="base_link_to_arm_base" type="fixed">
    <parent link="base_link"/>
    <child link="arm_base"/>
    <origin rpy="0 0 0" xyz="0 0 0.9"/>
  </joint>


  <link name="arm_shoulder_left">
    <visual>
      <origin rpy="0 0 0" xyz="0 ${-arm_base_size/2} ${arm_shoulder_size/2}"/>
      <geometry>
        <box size="${arm_base_size} ${arm_base_size} ${arm_shoulder_size}"/>
      </geometry>
    </visual>

    <xacro:box_inertial mass="${arm_mass}" length="${arm_base_size}" width="${arm_base_size}" heigth="${arm_base_size}"/>

    <buoyancy><compensation>1.0</compensation></buoyancy>
  </link>

  <joint name="arm_base_to_left_shoulder" type="fixed">
    <parent link="arm_base"/>
    <child link="arm_shoulder_left"/>
    <origin rpy="${alpha} 0 0" xyz="0 ${-arm_base_size/2} ${arm_base_size/2}"/>
  </joint>


  <link name="arm_knee">
    <visual>
      <origin rpy="0 0 0" xyz="0 ${arm_base_size/2} ${-arm_shoulder_size/2}"/>
      <geometry>
        <box size="${arm_base_size} ${arm_base_size} ${arm_shoulder_size}"/>
      </geometry>
    </visual>

    <xacro:box_inertial mass="${arm_mass}" length="${arm_base_size}" width="${arm_base_size}" heigth="${arm_base_size}"/>

    <buoyancy><compensation>1.0</compensation></buoyancy>
  </link>

  <joint name="arm_base_to_knee" type="revolute">
    <parent link="arm_shoulder_left"/>
    <child link="arm_knee"/>
    <axis xyz="1 0 0"/>
    <origin rpy="${PI/2-alpha} 0 0" xyz="0 0 ${arm_shoulder_size}"/>
    <dynamics damping="0.8"/>
    <limit lower="0" upper="${PI/2}" velocity="1" effort="500"/>
  </joint>


  <link name="arm_hand">
    <visual>
      <origin rpy="0 0 0" xyz="0 ${-arm_base_size/2} ${arm_hand_size/2}"/>
      <geometry>
        <box size="${arm_base_size} ${arm_base_size} ${arm_hand_size}"/>
      </geometry>
    </visual>

    <xacro:box_inertial mass="${arm_mass}" length="${arm_base_size}" width="${arm_base_size}" heigth="${arm_base_size}"/>

    <buoyancy><compensation>1.0</compensation></buoyancy>
  </link>

  <joint name="arm_knee_to_arm_hand" type="fixed">
    <parent link="arm_knee"/>
    <child link="arm_hand"/>
    <origin rpy="${2*PI/3} 0 0" xyz="0 0 ${-arm_shoulder_size}"/>
  </joint>
</robot>

