controllers:
  config:
    body:
      control_type: thruster  # cannot be wrench because of vectored thrusters
      state: state
      dynamic_reconfigure: False
    joints:
      state: joint_states
      setpoint: joint_setpoint
      command: joint_command
      cascaded_position: False
      dynamic_reconfigure: False
  OpenHook_arm0:
    velocity: {p: 1, i: 0.0, d: 2.0}
    position: {p: 10, i: 0.1, d: 0.5}
  OpenHook_arm1:
    velocity: {p: 1, i: 0.0, d: 2.0}
    position: {p: 10, i: 0.1, d: 0.5}
  OpenHook_arm2:
    velocity: {p: 1, i: 0.0, d: 2.0}
    position: {p: 10, i: 0.1, d: 0.5}
  OpenHook_arm3:
    velocity: {p: 1, i: 0.0, d: 2.0}
    position: {p: 10, i: 0.1, d: 0.5}
  OpenHook_arm4:
    velocity: {p: 1, i: 0.0, d: 2.0}
    position: {p: 10, i: 0.1, d: 0.5}
